version: '3'

networks:
  mainnetwork:
  driver: bridge

services:

 apiproxy:
  container-name: proxyapis
  build:
    context: ./PROXYS/PROXY-APIs
    dockerfile: ./PROXY/PROXY-APIs/Dockerfile
    ports:
      - 2020:2020
    depends_on:
      - api
      - authapi
    networks:
      - network1
  
  bffproxy:
    container-name: proxybff
    build:
      context: ./PROXYS/PROXY-BFFs
      dockerfile: ./PROXYS/PROXY-BFFs/Dockerfile
      ports:
      - 2050:2050
      depends_on:
      - bffdesk
      - bffmob
      networks:
      - network1

  api:
    container-name: entitiesapi
    build: ./APIs/API_Service
    dockerfile: ./APIs/API_Service/Dockerfile
    ports:
    - 2010:2010
    networks:
      - network1
  
  authapi:
    container-name: authapi
    build: ./APIs/AuthService
    dockerfile: ./APIs/AuthService/Dockerfile
    ports:
    - 2000:2000
    networks:
      - network1 
  
  bffdesk:
    container-name: deskbff
    build: ./BFFs/Desktop
    dockerfile: ./BFFs/Desktop/Dockerfile
    depends_on:
      - authapi
      - api
    ports:
    - 2030:2030

  bffmob:
    container-name: mobbff
    build: ./BFFs/Desktop
    dockerfile: ./BFFs/Desktop/Dockerfile
    depends_on:
      - authapi
      - api
    ports:
    - 2040:2040
    networks:
      - network1    